import type { Metadata } from "next";
import { Noto_Sans_TC } from "next/font/google";

import TopBar from "@/components/TopBar";
import FunctionBar from "@/components/FunctionBar";

import "./global.scss";

const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: {
      url: "/favicon.ico",
      type: "image/x-icon",
    },
    other: [
      {
        url: "/favicon.png",
        type: "image/png",
      },
      {
        url: "/favicon.svg",
        type: "image/svg+xml",
      }
    ]
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body> */}
      <body className={`${notoSansTC.variable}`}>
        <TopBar />
        {children}
        <FunctionBar />
      </body>
    </html>
  );
}
